export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="lambda"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(osx pip git)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all
unsetopt correct

# Customize to your needs...
HOME=/Users/alco
export PATH="/usr/local/bin:$PATH"
#export PATH="/Users/alco/Documents/git/rust/x86_64-apple-darwin/stage2/bin:$PATH"
#export PATH="/Developer/Marmalade/6.0/s3e/bin/:$PATH"
#export PATH="/usr/local/lib/ruby/gems/1.9.1/gems/cocoapods-0.5.1/bin:$PATH"
export PATH="/usr/local/lib/python3.4/site-packages:$PATH"
#export PATH="/Users/alco/home/goworkspace/bin:$PATH"
#export PATH="$PATH":/Users/alco/Documents/git/clojurescript/bin:/Users/alco/Documents/git/clojurescript/script
#export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
#export PATH="$HOME/.exenv/bin:$PATH"
if [ -e ~/home/bin ]; then
    export PATH="$HOME/home/bin:$PATH"
fi

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home
export PATH=$PATH:$JAVA_HOME/bin

export PYTHONPATH="/usr/local/lib/python3.4"
export NODE_PATH=/usr/local/lib/node_modules

export LESS="-FRX"  # interpret escape sequences and don't paginate when output is small
export ACK_PAGER="less $LESS"

alias ls='ls -G'
alias lsg='ls -Gg'
alias nfind='find . -name'

export GIT_EDITOR=vi
export SVN_EDITOR=$GIT_EDITOR

alias home="cd ~/home"

alias gco='git checkout'
alias gci='git commit'
alias grb='git rebase'
alias gad='git add'
alias gst='git status'
alias gamend='git commit --amend --no-edit'
alias gsync='git pull --prune source master'
alias gitpr='git push origin && hub browse'

alias ags='ag --ignore-dir test'
alias agi='ag -i'

alias cdgo='cd $GOPATH/src'

alias b2d=boot2docker
export DOCKER_HOST=tcp://localhost:2375

alias dockerrm='docker rm $(docker ps -aq)'
alias dockerprune='docker rmi $(docker images | grep "^<none>" | awk "{print \$3}")'

#alias svndiff='svn diff | colordiff | less -r'

#if [ -e /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin ]; then
#    export PATH=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:$PATH
#fi



## Completions
autoload -U compinit
compinit -C

## case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

godoc() {
    command godoc "$@" | less
}

# Change directory with bookmarks
#
function cdb_edit() {
    vim ~/.cdbookmarks
}

function cdb() {
    NewDir=`egrep "^$1:" ~/.cdbookmarks \
             | sed 's/^.*://'`;
    echo cd $NewDir
    cd $NewDir
}

function _cdb() {
    reply=(`cat ~/.cdbookmarks | sed 's/:.*$//'`);
}

compctl -K _cdb cdb

export GOPATH=$HOME/extra/goworkspace

#export JAVA_HOME=/Users/alco/Downloads/jre1.7.0_51.jre/Contents/Home

# OPAM configuration
#. /Users/alco/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
#
#eval "$(exenv init -)"

alias tnux='tmux new-session -s'

alias postgresql='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'

fpath=(~/home/bin/zsh/functions $fpath)
autoload $(ls ~/home/bin/zsh/functions)
